-- Table to store signals generated by strategies
CREATE TABLE IF NOT EXISTS signal_logs (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    strategy_id UUID NOT NULL, -- References the strategy that generated it
    symbol TEXT NOT NULL,
    action TEXT NOT NULL, -- 'BUY' or 'SELL'
    price NUMERIC,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    status TEXT DEFAULT 'PENDING', -- 'PENDING', 'PROCESSED', 'FAILED'
    metadata JSONB DEFAULT '{}'::jsonb
);

-- Enable Realtime for this table so backend can listen
ALTER PUBLICATION supabase_realtime ADD TABLE signal_logs;
