ALTER TABLE public.watchlists
ADD COLUMN IF NOT EXISTS lot_size NUMERIC DEFAULT 0.01,
ADD COLUMN IF NOT EXISTS risk_percent NUMERIC DEFAULT 1.0,
ADD COLUMN IF NOT EXISTS leverage NUMERIC DEFAULT 1,
ADD COLUMN IF NOT EXISTS stop_loss_distance NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS take_profit_distance NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS trailing_stop_loss_distance NUMERIC DEFAULT 0;
